"""Начальная схема: семьи, участники, задачи, события

Revision ID: fccf3da2ac1f
Revises:
Create Date: 2026-10-06 14:18:56.250997
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "fccf3da2ac1f"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "families",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("invite_code", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("invite_code"),
    )
    op.create_table(
        "members",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("family_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("has_car", sa.Boolean(), nullable=False),
        sa.Column("capacity_minutes", sa.Integer(), nullable=False),
        sa.Column("dislikes", sa.JSON(), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_members_family_id"), ["family_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_members_token"), ["token"], unique=True)

    op.create_table(
        "events",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("member_id", sa.String(length=32), nullable=False),
        sa.Column("family_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("props", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_events_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_family_id"), ["family_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_member_id"), ["member_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_events_name"), ["name"], unique=False)

    op.create_table(
        "tasks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("family_id", sa.String(length=32), nullable=False),
        sa.Column("created_by_id", sa.String(length=32), nullable=False),
        sa.Column("assignee_id", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("beneficiary", sa.String(length=80), nullable=True),
        sa.Column("due_at", sa.DateTime(), nullable=True),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=8), nullable=False),
        sa.Column("recurrence", sa.String(length=8), nullable=False),
        sa.Column("requires_car", sa.Boolean(), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("clarifying_question", sa.String(length=300), nullable=True),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("fairness_score", sa.Double(), nullable=True),
        sa.Column("vetoed_by", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assignee_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["members.id"],
        ),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tasks_family_id"), ["family_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tasks_family_id"))

    op.drop_table("tasks")
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_events_name"))
        batch_op.drop_index(batch_op.f("ix_events_member_id"))
        batch_op.drop_index(batch_op.f("ix_events_family_id"))
        batch_op.drop_index(batch_op.f("ix_events_created_at"))

    op.drop_table("events")
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_members_token"))
        batch_op.drop_index(batch_op.f("ix_members_family_id"))

    op.drop_table("members")
    op.drop_table("families")
    # ### end Alembic commands ###
