"""Вход по телефону: аккаунты и проверки звонком

Revision ID: 4d7a28d88c71
Revises: 1f1cebc580a1
Create Date: 2026-10-06 16:20:04.974299
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4d7a28d88c71"
down_revision: str | None = "1f1cebc580a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_accounts_phone"), ["phone"], unique=True)
        batch_op.create_index(batch_op.f("ix_accounts_token"), ["token"], unique=True)

    op.create_table(
        "phone_checks",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("provider_check_id", sa.String(length=64), nullable=False),
        sa.Column("call_phone", sa.String(length=20), nullable=False),
        sa.Column("call_phone_pretty", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_polled_at", sa.DateTime(), nullable=True),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("phone_checks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_phone_checks_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_phone_checks_ip"), ["ip"], unique=False)
        batch_op.create_index(batch_op.f("ix_phone_checks_phone"), ["phone"], unique=False)

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.String(length=32), nullable=True))
        batch_op.drop_index(batch_op.f("ix_members_token"))
        batch_op.create_unique_constraint("uq_members_account_id", ["account_id"])
        batch_op.create_foreign_key(
            "fk_members_account_id_accounts", "accounts", ["account_id"], ["id"]
        )
        batch_op.drop_column("token")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        # Старые сессии участников не восстанавливаются: колонка возвращается пустой
        batch_op.add_column(sa.Column("token", sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_constraint("fk_members_account_id_accounts", type_="foreignkey")
        batch_op.drop_constraint("uq_members_account_id", type_="unique")
        batch_op.create_index(batch_op.f("ix_members_token"), ["token"], unique=1)
        batch_op.drop_column("account_id")

    with op.batch_alter_table("phone_checks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_phone_checks_phone"))
        batch_op.drop_index(batch_op.f("ix_phone_checks_ip"))
        batch_op.drop_index(batch_op.f("ix_phone_checks_created_at"))

    op.drop_table("phone_checks")
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_token"))
        batch_op.drop_index(batch_op.f("ix_accounts_phone"))

    op.drop_table("accounts")
    # ### end Alembic commands ###
