"""Режим проверки просьбы перед отправкой

Revision ID: e07770f68450
Revises: 4a635af2fcdc
Create Date: 2026-10-09 21:25:15.118924
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "e07770f68450"
down_revision: str | None = "4a635af2fcdc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("confirm_mode", sa.String(length=8), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_column("confirm_mode")

    # ### end Alembic commands ###
