"""Согласие на обработку ПДн запоминается за номером

Revision ID: 47fccb742891
Revises: a2c9346b986e
Create Date: 2026-10-09 12:28:01.227375
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "47fccb742891"
down_revision: str | None = "a2c9346b986e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("consent_at", sa.DateTime(), nullable=True))

    # Все, кто уже вошёл, отмечали обязательную галочку согласия на экране входа
    op.execute("UPDATE accounts SET consent_at = created_at WHERE consent_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("consent_at")

    # ### end Alembic commands ###
