"""Статусы поручения: ждёт ответа / взял / сделано

Revision ID: ad9de952a5f2
Revises: 4d7a28d88c71
Create Date: 2026-10-06 16:47:25.435829
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ad9de952a5f2"
down_revision: str | None = "4d7a28d88c71"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("accepted_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("decline_reason", sa.String(length=300), nullable=True))
        batch_op.create_index(batch_op.f("ix_tasks_status"), ["status"], unique=False)
        batch_op.drop_column("vetoed_by")
        batch_op.drop_column("fairness_score")

    # «Открытые» задачи прежней модели — это поручения, которые ждут ответа
    op.execute("UPDATE tasks SET status = 'new' WHERE status = 'open'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE tasks SET status = 'open' WHERE status IN ('new', 'accepted')")
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("fairness_score", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("vetoed_by", sa.JSON(), nullable=True))
        batch_op.drop_index(batch_op.f("ix_tasks_status"))
        batch_op.drop_column("decline_reason")
        batch_op.drop_column("accepted_at")

    # ### end Alembic commands ###
