"""Спасибо за дело

Revision ID: 704aadafef8c
Revises: ab08b8f5ca50
Create Date: 2026-10-10 17:15:55.867282
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "704aadafef8c"
down_revision: str | None = "ab08b8f5ca50"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("thanked_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("thanked_at")

    # ### end Alembic commands ###
