"""Заметка к задаче

Revision ID: 3c8ec23a239c
Revises: e07770f68450
Create Date: 2026-10-09 21:39:55.119078
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "3c8ec23a239c"
down_revision: str | None = "e07770f68450"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("note", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("note")

    # ### end Alembic commands ###
