"""Тема оформления у участника

Revision ID: f38d4329d005
Revises: eec4c25f2227
Create Date: 2026-10-09 14:06:29.155805
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f38d4329d005"
down_revision: str | None = "eec4c25f2227"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(sa.Column("theme", sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_column("theme")

    # ### end Alembic commands ###
