"""Обращения к компонентам (component_calls)

Revision ID: 1f1cebc580a1
Revises: fccf3da2ac1f
Create Date: 2026-10-06 15:09:25.921875
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1f1cebc580a1"
down_revision: str | None = "fccf3da2ac1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "component_calls",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("operation", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("member_id", sa.String(length=32), nullable=True),
        sa.Column("family_id", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(
            ["family_id"],
            ["families.id"],
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("component_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_component_calls_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_component_calls_kind"), ["kind"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_component_calls_member_id"), ["member_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("component_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_component_calls_member_id"))
        batch_op.drop_index(batch_op.f("ix_component_calls_kind"))
        batch_op.drop_index(batch_op.f("ix_component_calls_created_at"))

    op.drop_table("component_calls")
    # ### end Alembic commands ###
