"""Напоминания перед сроком, «Я помню», список покупок

Revision ID: a2c9346b986e
Revises: a0e88fd69efc
Create Date: 2026-10-08 10:09:13.522512
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a2c9346b986e"
down_revision: str | None = "a0e88fd69efc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("remind_before_min", sa.Integer(), server_default="60", nullable=False)
        )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("items", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )
        batch_op.add_column(sa.Column("reminded_at", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("remembered_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("remembered_at")
        batch_op.drop_column("reminded_at")
        batch_op.drop_column("items")

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_column("remind_before_min")

    # ### end Alembic commands ###
