"""Сессии устройств, PIN-код, попытки входа

Revision ID: a0e88fd69efc
Revises: 3273eb7b958b
Create Date: 2026-10-07 10:08:50.452394
"""

import hashlib
import secrets
import uuid
from collections.abc import Sequence
from datetime import datetime

import sqlalchemy as sa
from alembic import op

revision: str = "a0e88fd69efc"
down_revision: str | None = "3273eb7b958b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ip", sa.String(length=64), nullable=True),
        sa.Column("phone", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_login_attempts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_login_attempts_ip"), ["ip"], unique=False)

    op.create_table(
        "sessions",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("account_id", sa.String(length=32), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("user_agent", sa.String(length=300), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sessions_account_id"), ["account_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sessions_token_hash"), ["token_hash"], unique=True)

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("pin_hash", sa.String(length=160), nullable=True))
        batch_op.add_column(
            sa.Column("pin_failures", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("pin_locked_until", sa.DateTime(), nullable=True))

    # Текущие сессии аккаунтов переносим в sessions — при выкатке никого не выбьет
    bind = op.get_bind()
    sessions = sa.table(
        "sessions",
        sa.column("id", sa.String),
        sa.column("account_id", sa.String),
        sa.column("token_hash", sa.String),
        sa.column("created_at", sa.DateTime),
        sa.column("last_used_at", sa.DateTime),
    )
    now = datetime.now()
    rows = [
        {
            "id": uuid.uuid4().hex,
            "account_id": account_id,
            "token_hash": hashlib.sha256(token.encode()).hexdigest(),
            "created_at": now,
            "last_used_at": now,
        }
        for account_id, token in bind.execute(
            sa.text("SELECT id, token FROM accounts WHERE token IS NOT NULL")
        )
    ]
    if rows:
        op.bulk_insert(sessions, rows)

    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_accounts_token"))
        batch_op.drop_column("token")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Сессии устройств в старой схеме не выразить — после отката все входят заново
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token", sa.VARCHAR(length=64), nullable=True))
    bind = op.get_bind()
    for (account_id,) in bind.execute(sa.text("SELECT id FROM accounts")).all():
        bind.execute(
            sa.text("UPDATE accounts SET token = :token WHERE id = :id"),
            {"token": secrets.token_urlsafe(32), "id": account_id},
        )
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.alter_column("token", existing_type=sa.VARCHAR(length=64), nullable=False)
        batch_op.create_index(batch_op.f("ix_accounts_token"), ["token"], unique=True)
        batch_op.drop_column("pin_locked_until")
        batch_op.drop_column("pin_failures")
        batch_op.drop_column("pin_hash")

    with op.batch_alter_table("sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sessions_token_hash"))
        batch_op.drop_index(batch_op.f("ix_sessions_account_id"))

    op.drop_table("sessions")
    with op.batch_alter_table("login_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_login_attempts_ip"))
        batch_op.drop_index(batch_op.f("ix_login_attempts_created_at"))

    op.drop_table("login_attempts")
    # ### end Alembic commands ###
