"""Участники дела

Revision ID: ab08b8f5ca50
Revises: 36aaec673017
Create Date: 2026-10-10 10:19:53.199841
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "ab08b8f5ca50"
down_revision: str | None = "36aaec673017"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("allow_participants", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("participants", sa.JSON(), nullable=False, server_default=sa.text("'[]'"))
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("participants")

    with op.batch_alter_table("members", schema=None) as batch_op:
        batch_op.drop_column("allow_participants")

    # ### end Alembic commands ###
