"""Окончание дела

Revision ID: 36aaec673017
Revises: 3c8ec23a239c
Create Date: 2026-10-09 21:55:35.919569
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "36aaec673017"
down_revision: str | None = "3c8ec23a239c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ends_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("ends_at")

    # ### end Alembic commands ###
