"""Отметка команды: не учитывается в метриках

Revision ID: eec4c25f2227
Revises: fb7115a95eee
Create Date: 2026-10-09 13:04:37.126556
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "eec4c25f2227"
down_revision: str | None = "fb7115a95eee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_team", sa.Boolean(), server_default=sa.text("0"), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounts", schema=None) as batch_op:
        batch_op.drop_column("is_team")

    # ### end Alembic commands ###
