"""Файлы к задачам

Revision ID: 4a635af2fcdc
Revises: c2bee8d27c1c
Create Date: 2026-10-09 16:08:44.169182
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4a635af2fcdc"
down_revision: str | None = "c2bee8d27c1c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "task_files",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("task_id", sa.String(length=32), nullable=False),
        sa.Column("uploaded_by_id", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("task_files", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_task_files_task_id"), ["task_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("task_files", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_task_files_task_id"))

    op.drop_table("task_files")
    # ### end Alembic commands ###
