"""«Не выполнено»: обратная связь исполнителю

Revision ID: c2bee8d27c1c
Revises: f38d4329d005
Create Date: 2026-10-09 14:46:29.272265
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "c2bee8d27c1c"
down_revision: str | None = "f38d4329d005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("feedback", sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column("feedback_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tasks", schema=None) as batch_op:
        batch_op.drop_column("feedback_at")
        batch_op.drop_column("feedback")

    # ### end Alembic commands ###
